# name: Main foodgram workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:13.10
#         env:
#           POSTGRES_USER: django_user
#           POSTGRES_PASSWORD: django_password
#           POSTGRES_DB: django_db
#         ports:
#           - 5432:5432
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: 3.9

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip 
#         pip install flake8==6.0.0
#         pip install -r ./backend/requirements.txt 
#     - name: Test with flake8
#       env:
#         POSTGRES_USER: django_user
#         POSTGRES_PASSWORD: django_password
#         POSTGRES_DB: django_db
#         DB_HOST: 127.0.0.1
#         DB_PORT: 5432
#       run: |
#         python -m flake8 backend/
#         cd backend/

#   build_and_push_to_docker_hub:
#     name: Push Docker image to DockerHub
#     runs-on: ubuntu-latest
#     needs: tests
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker 
#         uses: docker/login-action@v2
#         with:
#             username: ${{ secrets.DOCKER_USERNAME }}
#             password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Push to DockerHub backend
#         uses: docker/build-push-action@v4
#         with:
#           context: ./backend/
#           push: true
#           tags: lisaperevalova/foodgram_backend:latest

#   build_frontend_and_push_to_docker_hub:
#     name: Push frontend Docker image to DockerHub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker 
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Push to DockerHub frontend
#         uses: docker/build-push-action@v4
#         with:
#           context: ./frontend/
#           push: true
#           tags: lisaperevalova/foodgram_frontend:latest

#   build_gateway_and_push_to_docker_hub:
#     name: Push gateway Docker image to DockerHub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker 
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Push to DockerHub gateway
#         uses: docker/build-push-action@v4
#         with:
#           context: ./nginx/
#           push: true
#           tags: lisaperevalova/foodgram_gateway:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: 
#       - build_and_push_to_docker_hub
#       - build_frontend_and_push_to_docker_hub
#       - build_gateway_and_push_to_docker_hub
#     steps:
#     - name: Checkout repo
#       uses: actions/checkout@v3
#     - name: Copy docker-compose.yml via ssh
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USER }}
#         key: ${{ secrets.SSH_KEY }}
#         passphrase: ${{ secrets.SSH_PASSPHRASE }}
#         source: "docker-compose.production.yml"
#         target: "foodgram"
#     - name: Executing remote ssh commands to deploy
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USER }}
#         key: ${{ secrets.SSH_KEY }}
#         passphrase: ${{ secrets.SSH_PASSPHRASE }}
#         script: |
#           cd foodgram
#           # Выполняет pull образов с Docker Hub
#           sudo docker compose -f docker-compose.production.yml pull
#           # Перезапускает все контейнеры в Docker Compose
#           sudo docker compose -f docker-compose.production.yml down
#           sudo docker compose -f docker-compose.production.yml up -d
#           # Выполняет миграции и сбор статики
#           sudo docker compose -f docker-compose.production.yml exec backend python manage.py makemigrations
#           sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
#           sudo docker compose -f docker-compose.production.yml exec backend python manage.py load_ingredients
#           sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic
#           sudo docker compose -f docker-compose.production.yml exec backend cp -r /app/collected_static/. /backend_static/static/
#   send_message:
#     runs-on: ubuntu-latest
#     needs: deploy
#     steps:
#     - name: Send message
#       uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         message: Деплой успешно выполнен!
name: Main Foodgram Workflow

on:
  push:

jobs:
  backend_tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt

      - name: Test with flake8 and Django Tests
        env:
          POSTGRES_DB: foodgram
          POSTGRES_USER: foodgram_user
          POSTGRES_PASSWORD: foodgram_password
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          python -m flake8 backend/
          cd backend/
          python manage.py test

  build_backend_and_push_to_docker_hub:
    name: Push Backend Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: backend_tests

    steps:
      - name: Check out the Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Sign in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-back:latest

  build_frontend_and_push_to_docker_hub:
    name: Push Frontend Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Sign in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-front:latest

  build_gateway_and_push_to_docker_hub:
    name: Push Gateway Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Sign in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./infra/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram-proxy:latest

  deploy:
    name: Deploy Project on Remote Server
    runs-on: ubuntu-latest

    needs:
      - build_backend_and_push_to_docker_hub
      - build_frontend_and_push_to_docker_hub
      - build_gateway_and_push_to_docker_hub

    steps:
      - name: Check out the Repo
        uses: actions/checkout@v3

      - name: Copy `docker-compose.yml` via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "infra/docker-compose.production.yml"
          target: "foodgram"

      - name: Executing Remote SSH Commands to Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            npm cache clean --force
            sudo apt clean
            sudo journalctl --vacuum-time=1d
            sudo docker system prune -af
            cd foodgram
            sudo docker compose -f docker-compose.production.yml pull
            sudo docker compose -f docker-compose.production.yml down
            sudo docker compose -f docker-compose.production.yml up -d
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic
            sudo docker compose -f docker-compose.production.yml exec backend cp -r /app/collected_static/. /backend_static/static/
            sudo docker system prune -af

  send_telegram_message:
    name: Notify on Success in Telegram
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой успешно выполнен!
